apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ddddd
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ddddd
    spec:
      containers:
      - name: ddddd
        image: au.icr.io/shout/shout-test:1-master-488f7e8c-20190810083030
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ddddd
  labels:
    app: ddddd
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: ddddd